import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";
import NextAuthProvider from "@/components/Providers/NextAuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
import { WHATSAPPNUMBER, WHATSAPPNUMBERDISPLAY } from "./config/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Make my Premium",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </NextAuthProvider>
        <Link
          href={`https://api.whatsapp.com/send?phone=${WHATSAPPNUMBER}`}
          target="_blank"
          className="w-12 h-12 bg-contain fixed bottom-4 right-4 z-50"
          style={{ backgroundImage: "url(/whatsapp.png)" }}
        >
          <span className="absolute right-full bottom-0 mr-2 mb-2 text-lg text-green-600 bg-muted px-2 border rounded-lg whitespace-nowrap">
            {WHATSAPPNUMBERDISPLAY}
          </span>
        </Link>
      </body>
    </html>
  );
}
